import{a as P,S as B,i}from"./assets/vendor-Bt_EzQve.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))m(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const d of s.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&m(d)}).observe(document,{childList:!0,subtree:!0});function e(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function m(t){if(t.ep)return;t.ep=!0;const s=e(t);fetch(t.href,s)}})();const M="52838885-6d116f44af4c58ac8463c8402",$="https://pixabay.com/api/";async function p(o,r){const{data:e}=await P($,{params:{key:M,q:o,mage_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:r}});return e}const h=document.querySelector(".gallery"),g=document.querySelector(".load-more"),L=document.querySelector(".loader");let b=new B(".gallery a",{captionsData:"alt",captionDelay:300});function w(o){const r=o.map(e=>`
        <li class="gallery-item">
        <a href="${e.largeImageURL}">
            <img src="${e.webformatURL}" alt="${e.tags}"/>
        </a>
        <ul class="card">
            <li class="card-item"><b>Likes:</b> ${e.likes}</li>
            <li class="card-item"><b>Views:</b> ${e.views}</li>
            <li class="card-item"><b>Comments:</b> ${e.comments}</li>
            <li class="card-item"><b>Downloads:</b> ${e.downloads}</li>
        </ul>
        </li>`).join("");h.insertAdjacentHTML("beforeend",r),b.refresh()}function E(){h.innerHTML="",b.refresh()}function S(){L.classList.remove("is-hidden")}function v(){L.classList.add("is-hidden")}function q(){g.classList.remove("is-hidden")}function u(){g.classList.add("is-hidden")}const f=g,H=h,R=document.querySelector(".form"),y=R.querySelector("input[name='search-text']");let n="",c=1,l=0,a=0;R.addEventListener("submit",O);f.addEventListener("click",x);async function O(o){o.preventDefault();const r=y.value.trim();if(!r){i.warning({message:"Please enter a search term!",position:"topRight"});return}r!==n&&(n=r,c=1,a=0,l=0),E(),u(),S();try{const e=await p(n,c);if(l=e.totalHits||0,!e.hits||e.hits.length===0){i.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}w(e.hits),y.value="",a+=e.hits.length,a<l?q():(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch{i.error({message:"Something went wrong. Please try again later.",position:"topRight"})}finally{v()}}async function x(){f.disabled=!0,S(),c+=1;try{const o=await p(n,c);w(o.hits),a+=o.hits.length;const r=H.querySelector(".gallery-item");if(r){const{height:e}=r.getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}a>=(o.totalHits||l)?(u(),i.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):q()}catch{i.error({message:"Something went wrong while loading more images.",position:"topRight"})}finally{v(),f.disabled=!1}}
//# sourceMappingURL=index.js.map
